"use client";
import { useLanguage, LanguageSwitch } from '@/components/language';
import { useEffect, useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Github, Linkedin, Mail, MessageCircle, Download, Server, Cpu, Code2, Video, Network, Shield, MapPin } from 'lucide-react';
import { DepthField } from '@/components/depth-field';
import Image from 'next/image';
import { projects, categories } from '@/lib/projects';
const navLinks = [{ name: 'Proyectos', href: '#portfolio' }, { name: 'Servicios', href: '#services' }, { name: 'Sobre mí', href: '#about' }, { name: 'Contacto', href: '#contact' }];
const socials = [{ icon: Github, href: 'https://github.com/StarlinVilorio', label: 'GitHub' }, { icon: Linkedin, href: 'https://linkedin.com/in/starlin-vilorio-988016281', label: 'LinkedIn' }, { icon: Mail, href: 'mailto:starlin.newtron@gmail.com', label: 'Correo electrónico' }, { icon: MessageCircle, href: 'https://wa.me/18097916765', label: 'WhatsApp' }];
function SocialLinks() { const { t, language } = useLanguage(); return <div className="socials">{socials.map(s => <a key={s.label} href={s.href} aria-label={t(s.label)} target="_blank" rel="noopener noreferrer"><s.icon size={19}/></a>)}</div>; }
export function Navigation() {
    const { t, language } = useLanguage();
    const [open, setOpen] = useState(false);
    const [activeSection,setActiveSection]=useState('');
    useEffect(()=>{
      const entries=new Map<string,number>();
      const observer=new IntersectionObserver(changes=>{
       for(const entry of changes)entries.set(entry.target.id,entry.isIntersecting?entry.intersectionRatio:0);
       const current=[...entries].sort((a,b)=>b[1]-a[1])[0];
       setActiveSection(current&&current[1]>0?'#'+current[0]:'');
      },{rootMargin:'-10% 0px -35% 0px',threshold:[0,.05,.15,.4]});
      for(const link of navLinks){const el=document.querySelector(link.href);if(el)observer.observe(el)}
      return()=>observer.disconnect();
    },[]);
    useEffect(() => {
        const close = (e: KeyboardEvent) => {
            if (e.key === 'Escape') {
                setOpen(false);
                document.getElementById('menu-toggle')?.focus();
            }
        };
        if (open)
            window.addEventListener('keydown', close);
        return () => window.removeEventListener('keydown', close);
    }, [open]);
    return <><a href="#content" className="skip">{t("Saltar al contenido")}</a><header className="nav"><div className="shell nav-inner"><a href="#home" className="brand" aria-label={t("StarlinIT, inicio")}>{t("Starlin")}<span>{t("IT.")}</span></a><nav className="nav-links" aria-label={t("Navegaci\u00F3n principal")}>{navLinks.map(l => <a key={l.href} href={l.href} aria-current={activeSection===l.href?"location":undefined}>{t(l.name)}</a>)}</nav><div className="nav-controls"><a href="#contact" className="nav-contact">{t("Hablemos ")}<ArrowUpRight size={17}/></a><button id="menu-toggle" className="menu-toggle" aria-label={t(open ? 'Cerrar menú' : 'Abrir menú')} aria-expanded={open} aria-controls="mobile-nav" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><LanguageSwitch/></div></div>{open && <nav id="mobile-nav" className="mobile-nav" aria-label={t("Navegaci\u00F3n m\u00F3vil")}>{navLinks.map(l => <a key={l.href} href={l.href} aria-current={activeSection===l.href?"location":undefined} onClick={() => setOpen(false)}>{t(l.name)}</a>)}</nav>}</header></>;
}
export function Hero() { const { t, language } = useLanguage(); return <section id="home" className="hero shell"><div className="hero-meta"><p className="eyebrow">{t("Starlin Vilorio \u00B7 Portafolio")}</p><span className="availability">{t("Rep\u00FAblica Dominicana \u00B7 Trabajo remoto")}</span></div><div className="hero-layout"><div><h1><span className="title-line">{t("Ideas que se")}</span><span className="title-line">{t("convierten en")}</span><span className="title-line"><em>{t("tecnolog\u00EDa \u00FAtil.")}</em></span></h1><p className="hero-copy">{t("Soy Starlin. Conecto infraestructura, desarrollo e inteligencia artificial para construir herramientas y experiencias digitales con prop\u00F3sito.")}</p><div className="actions"><a href="#portfolio" className="button">{t("Explorar proyectos ")}<ArrowDown size={18}/></a><a href="/Starlin-Vilorio-CV.pdf" download className="button secondary">{t("Descargar CV ")}<Download size={18}/></a></div></div><div className="hero-stage"><DepthField/><div className="stage-grid" aria-hidden="true"/><div className="stage-orbits" aria-hidden="true"><i /><i /><i /></div><div className="stage-label" aria-hidden="true">{t("CREATIVE TECHNOLOGIST")}</div><div className="portrait"><Image src="/hero.webp" alt={t("Starlin Vilorio, especialista en tecnolog\u00EDa y creador digital")} fill sizes="(max-width:720px) 90vw, 40vw" priority/><div className="portrait-caption"><div><strong>{t("El creador detr\u00E1s del c\u00F3digo.")}</strong><span>{t("IT \u00B7 Desarrollo \u00B7 IA \u00B7 Audiovisual")}</span></div><ArrowUpRight size={28}/></div></div><div className="stage-coordinate" aria-hidden="true">{t("REP\u00DABLICA DOMINICANA")}<span>{t("DISE\u00D1AR / CONSTRUIR / CREAR")}</span></div></div></div><div className="hero-bottom"><div className="hero-facts"><div><strong>{t("13+")}</strong><span>{t("A\u00F1os en tecnolog\u00EDa")}</span></div><div><strong>{projects.length}</strong><span>{t("Proyectos y experiencias")}</span></div><div><strong>{t("4 \u00E1reas")}</strong><span>{t("Una visi\u00F3n conectada")}</span></div></div><SocialLinks /></div></section>; }
export function Portfolio() { const { t, language } = useLanguage(); const [active, setActive] = useState('Todos');
 useEffect(() => {
  let frame = 0;
  const reveal = (event: MouseEvent) => {
   const link = event.target instanceof Element ? event.target.closest<HTMLAnchorElement>('a[href^="#"]') : null;
   const id = link?.getAttribute('href')?.slice(1);
   if (!id || !projects.some(project => project.id === id)) return;
   setActive('Todos');
   cancelAnimationFrame(frame);
   frame = requestAnimationFrame(() => { frame = requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({block:'start',behavior:'instant'})); });
  };
  document.addEventListener('click', reveal);
  return () => { document.removeEventListener('click', reveal); cancelAnimationFrame(frame); };
 }, []);
 const filtered = projects.filter(p => active === 'Todos' || p.category === active); return <section id="portfolio" className="section shell"><div className="section-head"><div><p className="eyebrow">{t("01 / Trabajo seleccionado")}</p><h2>{t("Construir. Experimentar.")}<br />{t("Hacerlo realidad.")}</h2></div><p>{t("Desde sistemas que trabajan detr\u00E1s de escena hasta im\u00E1genes que cuentan una historia. Este es mi trabajo en acci\u00F3n.")}</p></div><div className="filters" role="group" aria-label={t("Filtrar proyectos por \u00E1rea")}>{categories.map(c => <button key={c} type="button" aria-pressed={active === c} onClick={() => setActive(c)}>{t(c)}</button>)}</div><div className="work-grid">{filtered.map((p) => <article key={p.id} id={p.id} className={`project ${p.featured ? 'featured' : ''}`}><div className={`project-visual ${p.tone} ${p.image ? "has-image" : ""}`}>{p.image && <Image src={p.image} alt={t(p.imageAlt || "Escenario de un bosque fantástico creado para el proyecto Despertar")} fill sizes="(max-width:720px) 90vw, 40vw"/>}<div className="visual-top"><span>{t(p.category)}</span><span>{String(projects.indexOf(p) + 1).padStart(2, '0')}</span></div>{!p.image && <div className="visual-symbol">{t(p.symbol)}</div>}{p.id === 'coral-graphic' && !p.image && <div className="pipeline" aria-label={t("Flujo: analizar, procesar y comparar")}><span>{t("Analizar")}</span>{t(" \u2192 ")}<span>{t("Procesar")}</span>{t(" \u2192 ")}<span>{t("Comparar")}</span></div>}</div><div className="project-body"><span className="status">{t(p.status)}</span><div className="project-heading"><h3>{t(p.title)}</h3></div><p>{t(p.description)}</p><div className="tags">{p.tags.map(tag => <span key={tag}>{t(tag)}</span>)}</div>{p.link && <a className="project-link" href={p.link} target="_blank" rel="noopener noreferrer" aria-label={`${t(p.linkLabel || "")}: ${t(p.title)}`}>{t(p.linkLabel || "Visitar proyecto")}<ArrowUpRight size={18}/></a>}</div></article>)}</div><p className="work-count" role="status" aria-live="polite">{filtered.length}{t(" de ")}{projects.length}{t(" proyectos y experiencias \u00B7 ")}{t(active)}</p></section>; }
export function Services() { const { t, language } = useLanguage(); const items = [{ icon: Server, title: 'Infraestructura y soporte', text: 'Administración de Windows y Linux, diagnóstico de incidencias y soporte técnico para que el trabajo siga avanzando.' }, { icon: Cpu, title: 'IA aplicada y automatización', text: 'Integración de modelos locales y flujos de trabajo para reducir tareas repetitivas y conectar herramientas.' }, { icon: Code2, title: 'Desarrollo de aplicaciones', text: 'Interfaces web y herramientas de escritorio que convierten una necesidad concreta en una experiencia sencilla.' }, { icon: Video, title: 'Creación audiovisual', text: 'Dirección visual, edición de video y exploración de IA para construir contenido con una identidad consistente.' }, { icon: Network, title: 'Redes y servicios cloud', text: 'Configuración DNS, conectividad, contenedores y publicación de servicios con acceso remoto.' }, { icon: Shield, title: 'Seguridad y acceso', text: 'Configuración de túneles, políticas de acceso y administración de servicios con atención a la seguridad.' }]; return <section id="services" className="section services"><div className="shell"><div className="section-head"><div><p className="eyebrow">{t("02 / C\u00F3mo puedo ayudarte")}</p><h2>{t("La idea es tuya.")}<br />{t("La construimos juntos.")}</h2></div><p>{t("Experiencia t\u00E9cnica y criterio creativo para acompa\u00F1ar tu proyecto desde el primer problema hasta la soluci\u00F3n.")}</p></div><article id="community-management" className="community-offer" aria-labelledby="community-title"><div><p className="offer-label">{t("Asesor\u00EDa para tu presencia digital")}</p><h3 id="community-title">{t("Community Management")}</h3><p>{t("Orientaci\u00F3n para marcas y emprendimientos que quieren dar el siguiente paso en redes sociales. Conversemos sobre tu presencia digital, tus contenidos y la relaci\u00F3n con tu comunidad.")}</p><p className="offer-training">{t("En la etapa final de mi formaci\u00F3n en Community Management.")}</p></div><div className="offer-action"><p className="offer-price">{t("US$75")}</p><p className="offer-unit">{t("Asesor\u00EDa")}</p><a className="button" href={'https://wa.me/18097916765?text=' + encodeURIComponent(t('Hola Starlin, me interesa tu asesoría en Community Management de US$75. Me gustaría conocer el alcance y la disponibilidad.'))} target="_blank" rel="noopener noreferrer">{t("Solicitar asesor\u00EDa ")}<ArrowUpRight size={18}/></a><p className="offer-note">{t("Coordinamos el alcance y la disponibilidad por WhatsApp.")}</p></div></article><div className="service-grid">{items.map((s, i) => <article className="service" key={s.title}><div className="service-number"><span>{t("0")}{i + 1}</span><s.icon size={25}/></div><h3>{t(s.title)}</h3><p>{t(s.text)}</p></article>)}</div></div></section>; }
export function About() { const { t, language } = useLanguage(); return <section id="about" className="section shell"><div className="about-grid"><div><p className="eyebrow">{t("03 / Sobre m\u00ED")}</p><h2>{t("La curiosidad")}<br />{t("es parte de")}<br />{t("mi trabajo.")}</h2><figure className="about-portrait"><Image src="/assets/portfolio/starlin-professional-portrait-v1.webp" alt={language==="en"?"Professional portrait of Starlin Vilorio":"Retrato profesional de Starlin Vilorio"} width={1000} height={1250} sizes="(max-width:720px) 90vw, 38vw"/></figure><div className="expertise">{['Hardware Support', 'Windows / Linux', 'Docker', 'Cloudflare', 'Python', 'React / Next.js', 'IA local', 'Community Management'].map(tag => <span key={tag}>{t(tag)}</span>)}</div></div><div className="about-copy"><p>{t("Actualmente trabajo como ")}<strong>{t("Hardware Support en Red Sail Technologies")}</strong>{t(", brindando soporte de hardware.")}</p><p>{t("Mi trayectoria empez\u00F3 resolviendo problemas de tecnolog\u00EDa. Con m\u00E1s de 13 a\u00F1os de experiencia en soporte y administraci\u00F3n de sistemas, aprend\u00ED a entender lo que las personas necesitan y a convertirlo en soluciones que puedan usar.")}</p><p>{t("Hoy llevo esa misma forma de trabajar a mis propios proyectos: plataformas multimedia, aplicaciones, automatizaci\u00F3n y creaci\u00F3n audiovisual con inteligencia artificial.")}</p><p>{t("Estoy en la etapa final de mi formaci\u00F3n en Community Management. Combino esta preparaci\u00F3n con mi experiencia en tecnolog\u00EDa y creaci\u00F3n audiovisual para asesorar a marcas y emprendimientos sobre su presencia en redes sociales.")}</p><p>{t("Trabajo desde Rep\u00FAblica Dominicana, con experiencia biling\u00FCe en espa\u00F1ol e ingl\u00E9s y apertura a proyectos y oportunidades remotas.")}</p><a href="https://linkedin.com/in/starlin-vilorio-988016281" className="button secondary" target="_blank" rel="noopener noreferrer">{t("Conoce mi trayectoria ")}<ArrowUpRight size={18}/></a></div></div></section>; }
export function Contact() {
    const { t, language } = useLanguage();
    const [notice, setNotice] = useState('');
    function submit(e: FormEvent<HTMLFormElement>) {
        e.preventDefault();
        const f = new FormData(e.currentTarget);
        const name = String(f.get('name') || '').trim(), email = String(f.get('email') || '').trim(), message = String(f.get('message') || '').trim();
        if (!name || !email || !message) {
            setNotice('Completa tu nombre, correo y mensaje.');
            return;
        }
        const body = language === "en" ? `Hi Starlin,\n\nMy name is ${name}.\nEmail: ${email}\nPhone: ${f.get('phone') || 'Not provided'}\n\n${message}` : `Hola Starlin,\n\nSoy ${name}.\nCorreo: ${email}\nTeléfono: ${f.get('phone') || 'No indicado'}\n\n${message}`;
        window.location.href = `mailto:starlin.newtron@gmail.com?subject=${encodeURIComponent(t(String(f.get('service'))))}&body=${encodeURIComponent(body)}`;
        setNotice('Se solicitó abrir tu aplicación de correo. Revisa el borrador y envíalo allí. Si no se abre, usa el correo o WhatsApp que aparece al lado.');
    }
    return <section id="contact" className="contact shell"><div className="contact-grid"><div><p className="eyebrow">{t("04 / Pr\u00F3ximo proyecto")}</p><h2>{t("\u00BFQu\u00E9 te gustar\u00EDa")}<br /><em>{t("hacer posible?")}</em></h2><p>{t("Cu\u00E9ntame tu idea, el problema que quieres resolver o la oportunidad que tienes en mente.")}</p><div className="direct-contact"><a href="mailto:starlin.newtron@gmail.com"><Mail size={19}/>{t("starlin.newtron@gmail.com")}</a><a href="https://wa.me/18097916765" target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>{t("+1 (809) 791-6765")}</a><span className="muted"><MapPin size={17} style={{ display: 'inline', marginRight: 8 }}/>{t("Rep\u00FAblica Dominicana \u00B7 Remoto")}</span></div></div><form className="form" onSubmit={submit}><div className="form-grid"><label>{t("Nombre")}<input name="name" autoComplete="name" required maxLength={100} placeholder={t("Tu nombre")}/></label><label>{t("Correo electr\u00F3nico")}<input name="email" type="email" autoComplete="email" required maxLength={200} placeholder={t("tu@correo.com")}/></label><label>{t("Tel\u00E9fono (opcional)")}<input name="phone" type="tel" autoComplete="tel" maxLength={40} placeholder={t("Tu n\u00FAmero de contacto")}/></label><label>{t("\u00BFEn qu\u00E9 puedo ayudarte?")}<select name="service" required defaultValue=""><option value="" disabled>{t("Selecciona un tema")}</option>{['Soporte técnico', 'Infraestructura y cloud', 'Desarrollo de aplicaciones', 'IA y automatización', 'Creación audiovisual', 'Asesoría en Community Management — US$75', 'Oportunidad laboral', 'Consulta general'].map(s => <option key={s} value={s}>{t(s)}</option>)}</select></label></div><label className="field">{t("Tu mensaje")}<textarea name="message" required maxLength={3000} rows={5} placeholder={t("Tengo una idea para\u2026")}/></label><p className="helper">{t("Este formulario prepara un borrador en tu aplicaci\u00F3n de correo.")}</p><button type="submit" className="button">{t("Preparar correo ")}<ArrowUpRight size={18}/></button><p role="status" className="helper">{t(notice)}</p></form></div></section>;
}
export function Footer() { const { t, language } = useLanguage(); return <footer className="footer"><div className="shell footer-inner"><a href="#home" className="brand">{t("Starlin")}<span>{t("IT.")}</span></a><p>{t("\u00A9 2026 Starlin Vilorio \u00B7 Tecnolog\u00EDa con prop\u00F3sito.")}</p><nav aria-label={t("Enlaces del pie")}><a href="#portfolio">{t("Proyectos")}</a><a href="https://github.com/StarlinVilorio" target="_blank" rel="noopener noreferrer">{t("GitHub \u2197")}</a><a href="#home">{t("Volver arriba \u2191")}</a></nav></div></footer>; }
