export type Project = {
    id: string;
    title: string;
    category: string;
    status: string;
    description: string;
    tags: string[];
    symbol: string;
    tone: string;
    link?: string;
    linkLabel?: string;
    featured?: boolean;
    image?: string;
    imageAlt?: string;
};
export const projects: Project[] = [
    { id: 'coral-graphic', title: 'Coral Better Graphic 2', category: 'IA y automatización', status: 'Aplicación de escritorio', description: 'Restauración y escalado de video con IA. Integra análisis del material, procesamiento en GPU, una cola que se puede pausar y reanudar, y comparación sincronizada del original con el resultado.', tags: ['Python', 'PyTorch', 'CUDA', 'Qt'], symbol: 'Coral 2.0', tone: 'art', featured: true, image: '/assets/portfolio/starlin-ai-workstation-v1.webp', imageAlt: 'Estación de trabajo para IA, restauración de video y desarrollo' },
    { id: 'despertar', title: 'Despertar', category: 'Creación audiovisual', status: 'Universo visual en desarrollo', description: 'Un proyecto narrativo de anime construido desde su identidad visual: personajes, escenarios y fotogramas clave. Una exploración de dirección artística y producción con IA.', tags: ['Dirección artística', 'Arte con IA', 'Narrativa'], symbol: 'DESPERTAR', tone: 'art', image: '/projects/despertar.webp' },
    { id: 'coral-ultra', title: 'Coral Ultra IA', category: 'IA y automatización', status: 'Ecosistema local', description: 'Un entorno propio que reúne modelos de IA, edición de imágenes, trabajos por lotes, monitoreo de hardware y herramientas de gestión en un panel central.', tags: ['Python', 'JavaScript', 'Ollama', 'ComfyUI'], symbol: 'Coral Ultra', tone: 'green' },
    { id: 'interpreter', title: 'Interpreter App', category: 'IA y automatización', status: 'Código abierto', description: 'Interpretación de voz español ↔ inglés en el equipo local, con subtítulos bilingües, captura de audio del navegador y aceleración por GPU. Distribuido como instalador para Windows.', tags: ['Whisper', 'MarianMT', 'CUDA', 'Vulkan'], symbol: 'ES ↔ EN', tone: 'blue', link: 'https://github.com/StarlinVilorio/interpreter-app', linkLabel: 'Explorar código' },
    { id: 'movierd', title: 'MovieRD', category: 'Infraestructura', status: 'Plataforma web', description: 'Desarrollo de una experiencia multimedia sobre infraestructura propia: interfaz web, integración con Jellyfin, acceso remoto y experiencia para Android TV.', tags: ['Next.js', 'Jellyfin', 'Cloudflare', 'Android TV'], symbol: 'MovieRD', tone: 'art', image: '/assets/portfolio/movierd-project-showcase-v1.webp', imageAlt: 'MovieRD en escritorio, tablet y móvil', link: 'https://movierd.com', linkLabel: 'Visitar proyecto' },
    { id: 'sabiasque', title: 'Sabías Que · Publicador', category: 'Creación audiovisual', status: 'Producción y automatización', description: 'Un flujo de trabajo para convertir guiones en piezas audiovisuales y organizar su publicación. Combina generación de video, montaje y programación de contenido para redes.', tags: ['Python', 'Video con IA', 'FFmpeg', 'Publicación'], symbol: '¿Sabías que?', tone: 'amber', link: 'https://starlinvilorio.github.io/sabiasque-publicador/', linkLabel: 'Ver página del proyecto' },
    { id: 'ingles', title: 'Inglés Sin Rodeos', category: 'Creación audiovisual', status: 'En preparación', description: 'Una serie de lecciones breves de inglés para redes sociales. El proyecto conecta guiones didácticos, una presentadora virtual y un formato audiovisual consistente.', tags: ['Contenido educativo', 'IA audiovisual', 'Edición'], symbol: 'Hello, world.', tone: 'blue' },
    { id: 'downloader', title: 'Coral Downloader', category: 'Aplicaciones', status: 'Aplicación de escritorio', description: 'Un gestor que centraliza descargas desde distintas fuentes en una interfaz de escritorio, con organización de la cola y una versión portable para Windows.', tags: ['Python', 'Windows', 'PyInstaller'], symbol: 'Coral ↓', tone: 'green' },
    { id: 'factura', title: 'Factura Electrónica RD', category: 'Aplicaciones', status: 'Prototipo en desarrollo', description: 'Base de un sistema de facturación para República Dominicana, con gestión de empresas, clientes y productos. Explora documentos XML/PDF y flujos de comprobantes electrónicos.', tags: ['Node.js', 'Express', 'Prisma', 'Docker'], symbol: 'e-CF / RD', tone: 'amber' },
    { id: 'cotizador', title: 'Cotizador por WhatsApp', category: 'IA y automatización', status: 'Prototipo local', description: 'Automatiza respuestas a consultas de hosting, dominios y certificados SSL mediante detección de palabras clave y un catálogo configurable de servicios.', tags: ['Python', 'WhatsApp Web', 'Automatización'], symbol: 'Hola → cotización', tone: 'green' },
    { id: 'android', title: 'StarlinIT · Android', category: 'Aplicaciones', status: 'Aplicación en desarrollo', description: 'La experiencia del portafolio llevada a Android, con pantallas para presentación, proyectos, currículum y contacto, desarrolladas con Kotlin y Jetpack Compose.', tags: ['Kotlin', 'Jetpack Compose', 'Android'], symbol: 'StarlinIT / app', tone: 'blue' },
    { id: 'reconstruccion', title: 'Reconstrucción cinematográfica', category: 'Creación audiovisual', status: 'Investigación y desarrollo', description: 'Exploración de una cadena de trabajo para transformar escenas de animación en una estética cinematográfica, manteniendo composición, cámara y continuidad temporal.', tags: ['Visión artificial', 'Video con IA', 'Composición'], symbol: 'Frame → escena', tone: 'purple' },
    { id: 'copiador', title: 'Panel de procesamiento multimedia', category: 'IA y automatización', status: 'Herramienta interna', description: 'Herramientas locales para organizar el procesamiento y la copia de archivos multimedia, con un panel web y scripts que coordinan las tareas.', tags: ['Python', 'HTML', 'Automatización'], symbol: 'Media / Ops', tone: 'blue' },
    { id: 'dns', title: 'Administración DNS', category: 'Infraestructura', status: 'Experiencia profesional', description: 'Configuración y diagnóstico de DNS, resolución de incidencias y soporte a entornos empresariales. Una base técnica para mantener servicios web y correo accesibles.', tags: ['DNS', 'Redes', 'Soporte técnico'], symbol: 'DNS / IT', tone: 'amber' },
    { id: 'homelab', title: 'Home Lab Stack', category: 'Infraestructura', status: 'Infraestructura propia', description: 'Un laboratorio de servicios alojados en equipos propios, con contenedores y administración centralizada para experimentar, integrar y mantener aplicaciones.', tags: ['Docker', 'Portainer', 'Windows', 'Linux'], symbol: 'Self-hosted.', tone: 'green' },
    { id: 'zerotrust', title: 'Acceso remoto con Cloudflare', category: 'Infraestructura', status: 'Infraestructura propia', description: 'Configuración de túneles y políticas de acceso para conectar servicios internos con dominios públicos, junto con administración de DNS y protección del acceso remoto.', tags: ['Cloudflare Tunnel', 'Zero Trust', 'DNS'], symbol: 'Local ↔ Cloud', tone: 'blue' },
    { id: 'media', title: 'Automatización multimedia', category: 'Infraestructura', status: 'Flujo de trabajo local', description: 'Integración de servicios para organizar bibliotecas multimedia, metadatos y subtítulos, reduciendo tareas repetitivas en la administración del servidor.', tags: ['Radarr', 'Sonarr', 'Bazarr', 'Prowlarr'], symbol: 'Media / Flow', tone: 'purple' },
    { id: 'starlinit', title: 'StarlinIT.com', category: 'Aplicaciones', status: 'Sitio publicado', description: 'Mi portafolio profesional: una experiencia responsive que reúne infraestructura, software y creación audiovisual, con exportación estática y dominio propio.', tags: ['Next.js', 'React', 'TypeScript', 'GitHub Pages'], symbol: 'StarlinIT.', tone: 'coral', link: 'https://github.com/StarlinVilorio/portafolio-source', linkLabel: 'Explorar código' },
    { id: 'calculadora', title: 'Calculadora web', category: 'Aplicaciones', status: 'Proyecto de práctica', description: 'Una calculadora de operaciones básicas y decimales con controles de teclado. Un ejercicio de interfaz responsive y lógica en JavaScript sin frameworks.', tags: ['HTML', 'CSS', 'JavaScript'], symbol: '12 + 8 = 20', tone: 'amber' },
];
export const categories = ['Todos', ...Array.from(new Set(projects.map(p => p.category)))];
